version: 0.1.{build}-{branch}
pull_requests:
  do_not_increment_build_number: true
skip_non_tags: true
max_jobs: 1
platform:
  - x86
  - Any CPU
  - x64

configuration:
  - Debug
  - Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- ps: nuget restore beam-client-csharp.sln
build:
  parallel: true
  verbosity: minimal
deploy:
- provider: GitHub
  auth_token:
    secure: J23h13Yo4W+yv7Z4aTH9/d6K5mhV05LmT7bmQgE8xvF82clg21mSCataOjrQX0uV
  artifact: beam-client-csharp/bin/Release/beam-client-csharp.dll
  prerelease: false
  force_update: false
  on:
    branch: master